[package]
name = "xtask"
version = "0.1.0"
authors = ["mechiru <u9053u6d41@gmail.com>"]
edition = "2018"

[dependencies]
tonic-build = { version = "0.4", default-features = false, features = ["rustfmt", "prost"] }
prost-build = "0.7"
